// <auto-generated />
namespace WebMVCApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredAddedRemoved1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredAddedRemoved1));
        
        string IMigrationMetadata.Id
        {
            get { return "201602230130225_requiredAddedRemoved1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
